### ISSUE TITLE
<HOME> action is inconsistent if cursor is already at beginning of line

### ISSUE THREAD

**Issue by AvidGameFan** [montgomerybc/brief-keymap#2]
If you are in the middle of a line, pressing <HOME> once gets you to the BOL, twice to the top of the screen, and 3 times to the top of file.  If the cursor is already at the beginning, pressing <HOME> once takes you to the top of the screen, but really, two presses should always be top-of-screen, I think, to keep it consistent.

I can provide a pull-request to fix this, but I don't have access.

This problem exists for <END> as well, but it has another problem of inconsistent operation.  I have not modified the code for <END> but it probably can be changed to match what I did for <HOME>.

**Comment by montgomerybc** [comment]
Yeah, the window positioning API were quite limited back then.  I believe they've added new ones/fixed the existing ones making my hack state engine unnecessary.  I'll open up the pull requests (assuming I can figure out how.)

**Comment by dnanian** [comment]
The Home and End key behavior has always been one of the subtle things that BRIEF emulations tend to get wrong... :)

Looking forward to seeing how far you get with this.

**Comment by AvidGameFan** [comment]
I made a few changes to Home, and I don't know if they are accurate to the original BRIEF behavior, but they are to my liking.  :-)  End seemed to work better from the start, so I don't think I messed with that yet.

I'm a bit short on time at the moment, but I'll revisit in a couple of weeks or so and get a pull request going.

**Comment by montgomerybc** [comment]
FYI: I just pushed a change that should match the original Brief implementation.

**Comment by dnanian** [comment]
I wish I could remember what I used as the exact delay for the home/end timeout (apart from the obvious sequential part). It's critical, though, to not use position as what to "key off" for what to do - even if you're at the beginning of the line, on first press Home should go the the beginning of the line -- in that case, not move. Similarly, Home,Home should always go top left, even if you were already at SOL, etc.

You'll definitely "feel" it when you get it right... :-)

**Comment by montgomerybc** [comment]
Thanks.  I needed to run brief in a DOSBox to try this out -- exactly as
you describe.  I've updated the project to (hopefully) match the original
brief behaviour.

-Dave

**Comment by montgomerybc** [comment]
4f6235a
